package simulador;

import javax.swing.JTextField;
import static simulador.Simulador.frame;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_tempo_pecas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Dist_normal_tb = new javax.swing.JTextField();
        Fixa_seed_tb = new javax.swing.JTextField();
        Prep_seed_tb = new javax.swing.JTextField();
        Prep_desvio_tb = new javax.swing.JTextField();
        Fixa_desvio_tb = new javax.swing.JTextField();
        Fixa_media_tb = new javax.swing.JTextField();
        Prep_media_tb = new javax.swing.JTextField();
        Teste_media_tb = new javax.swing.JTextField();
        Teste_seed_tb = new javax.swing.JTextField();
        Teste_desvio_tb = new javax.swing.JTextField();
        run_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados_area = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        Prep_maq_tb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Fixa_maq_tb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Teste_maq_tb = new javax.swing.JTextField();
        Tempo_rb = new javax.swing.JRadioButton();
        Pecas_rb = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Tempo_pecas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Media_Dist_normal_tb = new javax.swing.JTextField();
        exe_d_ii = new javax.swing.JRadioButton();
        seed_exed = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ex1 = new javax.swing.JLabel();
        ex2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seed Dist. Normal:");

        jLabel2.setText("Preparação");

        jLabel3.setText("-Media:");

        jLabel4.setText("-Desvio Padrão:");

        jLabel5.setText("-Seed:");

        jLabel6.setText("Fixação");

        jLabel7.setText("-Media:");

        jLabel8.setText("-Desvio Padrão:");

        jLabel9.setText("-Seed:");

        jLabel10.setText("Teste");

        jLabel11.setText("-Media:");

        jLabel12.setText("-Desvio Padrão:");

        jLabel13.setText("-Seed:");

        Dist_normal_tb.setText("5");

        Fixa_seed_tb.setText("9");

        Prep_seed_tb.setText("3");

        Prep_desvio_tb.setText("1.5");

        Fixa_desvio_tb.setText("1.3");

        Fixa_media_tb.setText("5");

        Prep_media_tb.setText("6");

        Teste_media_tb.setText("4.5");

        Teste_seed_tb.setText("1");

        Teste_desvio_tb.setText("1.1");

        run_button.setText("Corre");
        run_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_buttonActionPerformed(evt);
            }
        });

        Resultados_area.setColumns(20);
        Resultados_area.setRows(5);
        jScrollPane1.setViewportView(Resultados_area);

        jLabel15.setText("-Máquinas:");

        Prep_maq_tb.setText("1");

        jLabel16.setText("-Máquinas:");

        Fixa_maq_tb.setText("1");

        jLabel17.setText("-Máquinas:");

        Teste_maq_tb.setText("1");

        Grupo_tempo_pecas.add(Tempo_rb);
        Tempo_rb.setText("Tempo");

        Grupo_tempo_pecas.add(Pecas_rb);
        Pecas_rb.setSelected(true);
        Pecas_rb.setText("Peças");

        jLabel18.setText("Quantidade:");

        Tempo_pecas.setText("1000");

        jLabel19.setText("Média Dist. Normal:");

        Media_Dist_normal_tb.setText("5");

        exe_d_ii.setText("Exercicio d. ii)");
        exe_d_ii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exe_d_iiActionPerformed(evt);
            }
        });

        seed_exed.setText("4");

        jLabel14.setText("Seed:");

        ex1.setText("Média: 2.25");

        ex2.setText("Desvio padrão: 0.5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel17))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Teste_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fixa_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Dist_normal_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Prep_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Prep_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Prep_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fixa_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fixa_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Teste_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Teste_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Prep_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Fixa_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Teste_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Tempo_rb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Pecas_rb))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(3, 3, 3)
                                    .addComponent(Tempo_pecas)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Media_Dist_normal_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 86, Short.MAX_VALUE)
                                .addComponent(ex1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ex2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seed_exed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(run_button)
                                .addGap(105, 105, 105)
                                .addComponent(exe_d_ii)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Dist_normal_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run_button)
                    .addComponent(exe_d_ii))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seed_exed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(ex1)
                            .addComponent(ex2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(Media_Dist_normal_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Prep_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Prep_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Prep_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Prep_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Fixa_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Fixa_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Fixa_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Fixa_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Teste_media_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Teste_desvio_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Teste_seed_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Teste_maq_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tempo_rb)
                            .addComponent(Pecas_rb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Tempo_pecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void run_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_buttonActionPerformed
        Resultados_area.setText("");
        Simulador s = new Simulador();
        if (frame.getExed_on())
                s.exed_on=1;
        s.executa();
    }//GEN-LAST:event_run_buttonActionPerformed

    private void exe_d_iiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exe_d_iiActionPerformed
        if (exe_d_ii.isSelected()){
            Fixa_media_tb.enable(false);
            Fixa_desvio_tb.enable(false);
            Fixa_seed_tb.enable(false);
            Fixa_maq_tb.enable(false);
            Teste_seed_tb.enable(false);
            Teste_desvio_tb.enable(false);
            Teste_media_tb.enable(false);
            Teste_maq_tb.enable(false);
            ex1.setVisible(true);
            ex2.setVisible(true);
            Prep_media_tb.setText("2");
            Prep_media_tb.enable(false);
            Prep_desvio_tb.setText("0.5");
            Prep_desvio_tb.enable(false);
            Prep_maq_tb.setText("1");
            Prep_maq_tb.enable(false);
        }
        else{
            Fixa_media_tb.enable(true);
            Fixa_desvio_tb.enable(true);
            Fixa_seed_tb.enable(true);
            Teste_seed_tb.enable(true);
            Teste_desvio_tb.enable(true);
            Teste_media_tb.enable(true);
            Fixa_maq_tb.enable(true);
            Teste_maq_tb.enable(true);
            ex1.setVisible(false);
            ex2.setVisible(false);
            Prep_media_tb.enable(true);
            Prep_desvio_tb.enable(true);
            Prep_maq_tb.enable(true);
        }
    }//GEN-LAST:event_exe_d_iiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public void SetResultados(String x){
        String tmp;
        tmp = Resultados_area.getText();
        tmp = tmp+"\n\n"+x;
        Resultados_area.setText(tmp);
    }

    public int getDist_normal_tb() {
        return Integer.parseInt(Dist_normal_tb.getText());
    }
    public double getMedia_Dist_normal_tb(){
        return Double.parseDouble(Media_Dist_normal_tb.getText());
    }
    public double getFixa_desvio_tb() {
        return Double.parseDouble(Fixa_desvio_tb.getText());
    }
    public double getFixa_media_tb() {
        return Double.parseDouble(Fixa_media_tb.getText());
    }
    public int getFixa_seed_tb() {
        return Integer.parseInt(Fixa_seed_tb.getText());
    }
    public double getPrep_desvio_tb() {
        return Double.parseDouble(Prep_desvio_tb.getText());
    }
    public double getPrep_media_tb() {
        return Double.parseDouble(Prep_media_tb.getText());
    }
    public int getPrep_seed_tb() {
        return Integer.parseInt(Prep_seed_tb.getText());
    }
    public double getTeste_desvio_tb() {
        return Double.parseDouble(Teste_desvio_tb.getText());
    }
    public double getTeste_media_tb() {
        return Double.parseDouble(Teste_media_tb.getText());
    }
    public int getTeste_seed_tb() {
        return Integer.parseInt(Teste_seed_tb.getText());
    }
    public int getPrep_maq_tb() {
        return Integer.parseInt(Prep_maq_tb.getText());
    }
    public int getFixa_maq_tb() {
        return Integer.parseInt(Fixa_maq_tb.getText());
    }
    public int getTeste_maq_tb() {
        return Integer.parseInt(Teste_maq_tb.getText());
    }
    public int getTempo_rb(){
        if (Tempo_rb.isSelected())
            return 1;
        else
            return 0;
    }
    public int getPecas_rb(){
        if (Pecas_rb.isSelected()){
            return 1;
        }
        else
            return 0;
    }
    public int getTempoPecas(){
        return Integer.parseInt(Tempo_pecas.getText());
    }
    
    public int getSeed_exed(){
        return Integer.parseInt(seed_exed.getText());
    }
    
    public boolean getExed_on(){
        return exe_d_ii.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dist_normal_tb;
    private javax.swing.JTextField Fixa_desvio_tb;
    private javax.swing.JTextField Fixa_maq_tb;
    private javax.swing.JTextField Fixa_media_tb;
    private javax.swing.JTextField Fixa_seed_tb;
    private javax.swing.ButtonGroup Grupo_tempo_pecas;
    private javax.swing.JTextField Media_Dist_normal_tb;
    private javax.swing.JRadioButton Pecas_rb;
    private javax.swing.JTextField Prep_desvio_tb;
    private javax.swing.JTextField Prep_maq_tb;
    private javax.swing.JTextField Prep_media_tb;
    private javax.swing.JTextField Prep_seed_tb;
    private javax.swing.JTextArea Resultados_area;
    private javax.swing.JTextField Tempo_pecas;
    private javax.swing.JRadioButton Tempo_rb;
    private javax.swing.JTextField Teste_desvio_tb;
    private javax.swing.JTextField Teste_maq_tb;
    private javax.swing.JTextField Teste_media_tb;
    private javax.swing.JTextField Teste_seed_tb;
    private javax.swing.JLabel ex1;
    private javax.swing.JLabel ex2;
    private javax.swing.JRadioButton exe_d_ii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton run_button;
    private javax.swing.JTextField seed_exed;
    // End of variables declaration//GEN-END:variables
}
